---
name: Update arxiv.org stats
on:
  schedule:
    # https://crontab.guru/every-day
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  OUT_DIR: './data'
  APP_DIR: './app'
  PY_VER: '3.10'
jobs:
  updateArxivCsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4     
      - name: Setup python ${{ env.PY_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          cache: 'pip'
      - run: pip install -qqr ${{ env.APP_DIR }}/requirements.txt
      - run: python ${{ env.APP_DIR }}/app.py
      - name: Check if there are any changes
        id: diff_check_changed
        run: |
          git add $OUT_DIR
          git diff --cached --quiet
          test $? -eq 1 && echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit and push if changes
        if: steps.diff_check_changed.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $OUT_DIR
          git commit -m "Updated $OUT_DIR"
          git push
...
