---
name: Update arxiv.org stats
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  CSV_FILE: data/dummy-data.csv
jobs:
  updateArxivCsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: $CSV_FILE
          sparse-checkout-cone-mode: false
      # fetch statistics for arxiv.org
      # https://github.com/karpathy/arxiv-sanity-lite/blob/master/aslite/arxiv.py#L38
      #- name: download data from arxiv API
      - name: save data to csv
        uses: gr2m/write-csv-file-action@v1.x
        with:
          # https://github.com/marketplace/actions/write-to-csv-file
          path: $CSV_FILE
          columns: id, version, time, time_str
          id: $RANDOM$RANDOM$RANDOM
          version: v$RANDOM
          time: $(date -u +"%H:%M:%S %Z")
          time_str: $( date +%s )
      - name: push updated file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $CSV_FILE
          git commit -m "Updated $CSV_FILE"
          git push origin main
...
