---
name: Update arxiv.org stats
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  CSV_PATH: data
  CSV_NAME: dummy-data.csv
jobs:
  updateArxivCsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: data/dummy-data.csv
          sparse-checkout-cone-mode: false
      # fetch statistics for arxiv.org
      # https://github.com/karpathy/arxiv-sanity-lite/blob/master/aslite/arxiv.py#L38
      #- name: download data from arxiv API
      - name: save data to csv
        uses: gr2m/write-csv-file-action@v1.x
        with:
          # https://github.com/marketplace/actions/write-to-csv-file
          path: data/dummy-data.csv
          columns: id, version, time, time_str
          id: 1
          version: 1
          time: "2024-06-01T19:32:58Z"
          time_str: 1717270378
      - name: push updated file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data
          git commit -m "Updated data/dummy-data.csv"
          git push origin main
...
