---
name: Update arxiv.org stats
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  CSV_FILE: data/dummy-data.csv
jobs:
  updateArxivCsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      #  with:
      #    sparse-checkout: $CSV_FILE
      #    sparse-checkout-cone-mode: false
      # fetch statistics for arxiv.org
      # https://github.com/karpathy/arxiv-sanity-lite/blob/master/aslite/arxiv.py#L38
      #- name: download data from arxiv API
      - name: save data to csv
        run: |
          if [[ ! -f "$CSV_FILE" ]]; then
            echo "id,version,time,time_str" >$CSV_FILE
          fi
          id=$RANDOM$RANDOM$RANDOM
          version=$RANDOM
          time=$(date -u +"%H:%M:%S %Z")
          time_str=$( date +%s )
          echo "$id,$version,$time,$time_str" >>$CSV_FILE
      - name: push updated csv file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $CSV_FILE
          git commit -m "Updated $CSV_FILE"
          git push origin main
...
